
name: CI Pipeline

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  source:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Check out code
        uses: actions/checkout@v4
        with:
          submodules: true
          
      - name: Update Submodules
        run: git submodule update --init --recursive

      # Step 2: Branch protection checks
      - name: Branch Protection Checks
        run: |
          # Prevent direct pushes to the main branch
          if [[ "${GITHUB_REF}" == "refs/heads/main" && "${GITHUB_EVENT_NAME}" == "pull_request" ]]; then
            echo "Direct pushes to main are not allowed."
            exit 1
          fi

        # Step 3: Run Linter (clang-tidy)
      - name: Linting with clang-tidy
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-tidy
          rm -rf build/*
          mkdir -p build
          cd build
          cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON ..
          cd ..
          # Run clang-tidy on all .cpp files in src and tests directories, excluding Main.cpp
          for file in src/*.cpp tests/*.cpp; do
              if [[ "$file" != "src/Main.cpp" ]]; then
                  clang-tidy "$file" --warnings-as-errors=* -p build
              fi
          done


       # Step 4: Static Code Analysis with cppcheck
      - name: Static Code Analysis with cppcheck
        run: |
          sudo apt-get install -y cppcheck
          cppcheck --enable=all src tests


  build:
    runs-on: ubuntu-latest
    
    needs: source

    steps:
      # Step 1: Check out the code
      - name: Check out code
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Update Submodules
        run: git submodule update --init --recursive

      # Step 2: Install dependencies
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake valgrind gcovr libgl1-mesa-dev

      # Step 3: Configure and build with CMake
      - name: Build Project
        run: |
          rm -rf build/*
          mkdir -p build
          cd build
          cmake ..
          make

      # Step 4: Run Unit Tests
      - name: Run Unit Tests
        run: |
          cd build
          ./tests

      # Step 5: Memory Leak Check with Valgrind
      - name: Memory Leak Check with Valgrind
        run: |
          cd build
          valgrind --leak-check=full --error-exitcode=1 ./tests


      # Step 6: Code Coverage with gcov/gcovr
      - name: Code Coverage with gcov/gcovr
        run: |
          cd build
          make clean
          cmake -DCMAKE_BUILD_TYPE=Debug -DENABLE_COVERAGE=ON ..
          make
          ./tests # Run tests to generate coverage data
          gcovr -r .. --xml-pretty --output coverage.xml # Generate coverage report
